### ISSUE TITLE
Local docker name-mismatch

### ISSUE THREAD

**Issue by epsteinmark** [RoryHemmings/cyber-rootkit-s23#4]
The docker instance created running ``sudo make setup`` when trying to run the project locally is target-mw-target-1. The docker connection attempt when running ``sudo make shell`` is remote_target-mw-target-1. This leads to a connection error.

Suggested fix:
Modify the Makefile shell rule to target-mw-target-1.

**Comment by RoryHemmings** [comment]
This occurred because I was testing the environment in a different directory called remote_target within the private bleeding edge repo for this project. I just copy and pasted the code into this repo and forgot to change the makefile lol. I'll fix it.

**Comment by RoryHemmings** [comment]
https://github.com/RoryHemmings/cyber-rootkit-s23/commit/4318d9983b9b8c590574c6a08bce51c73f0be578
